<!DOCTYPE html>
<html>
<head>
	<title> INDEX</title>
	<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
		<h1>Bon de commande</h1>
		

		<table>
		<caption>Liste des commandes</caption>

		<thead>
			<tr>
				<th>Commande</th>
				<th>Date de la commade</th>
				<th>Date de livraison</th>
				<th>Statut</th>
			</tr>
		</thead>


		<tbody>
			<tr>
				<td>aaa</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>aaa</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
			
		</table>
</body>
</html>