

<main id=addpost class="container">
	<h2>Création dun compte client</h2>

	<form class="generic-form" method="POST" action="<?= $requestUrl ?>/user">
		<fieldset>
			<legend>Identité et coordonnées</legend>

			<ul>

			<li>
			<label for="Nom">Nom:</label>
			<input type="text" name="nom">
			</li>

			<li>
			<label for="Prénom">Prénom:</label>
			<input type="text" name="prenom">
			</li>

			<li>
			<label for="date">Date de naissance:</label>

			
			<select name="jour">
				<?php for($day = 1; $day <= 31; $day++) {?>
			    	<option value="<?= $day ?>"><?= $day ?></option> 
			    <?php } ?>
			</select>
			<select name="mois">
			    <option value="1">Janvier</option>
			    <option value="2">Février</option>
			    <option value="3">Mars</option>
			    <option value="4">Avril</option>
			    <option value="5">Mai</option>
			    <option value="6">Juin</option>
			    <option value="7">Juillet</option>
			    <option value="8">Aout</option>
			    <option value="9">Septembre</option>
			    <option value="10">Octobre</option>
			    <option value="11">Novembre</option>
			    <option value="12">Décembre</option>
			</select>
			<select name="annee">
			<?php for($year = 1960; $year <= 2015; $year++) {?>
			    	<option value="<?= $year ?>"><?= $year ?></option> 
			    <?php } ?>
			   
			</select>
			</li>

			<li>
			<label for="adresse">Adresse:</label>
			<textarea name="adresse" rows="10" cols="50" value=""></textarea>
			</li>


			<li>
			<label for="ville">Ville:</label>
			<input type="text" name="ville">
			</li>


			<li>
			<label for="code">Code Postal:</label>
			<input type="text" name="code">
			</li>


			<li>
			<label for="tel">Téléphone:</label>
			<input type="tel" name="tel">
			</li>

			</ul>

		</fieldset>
		

		
		<fieldset>
			<legend>Information D'authencification</legend>

		<ul>
		<li>
		<label for="mail">e-mail :</label>
        <input type="email" id="mail" name="mail">
        </li>

        <li>
        <label for="password">Mot de Passe :</label>
        <input type="password" name="password" id="password" />
        </li>

        </ul>
		</fieldset>	
			<div >
				<input class="button" type="submit" value="Créer un compte" />
				<input class="button" type="reset" value="Annuler" />
		</div>
		</form>

	
	
</main>
