<main>
	<h2>Se connecter avec un compte utilisateur</h2>

	<form class="generic-form" method="POST" action="<?= $requestUrl ?>/user/login">
	<fieldset>
			<legend>Information D'authencification</legend>

		<ul>
		<li>
		<label for="mail">e-mail :</label>
        <input type="email" id="mail" name="mail">
        </li>

        <li>
        <label for="password">Mot de Passe :</label>
        <input type="password" name="password" id="password" />
        </li>

        </ul>
		</fieldset>	
			<div >
				<input class="button" type="submit" value="Connexion" />
				<input class="button" type="reset" value="Annuler" />
		</div>
		</form>
</main>