<h2><i class="fa fa-star"></i> Commande payée</h2>

<h3>Merci d'avoir commandé au 3WA Restaurant !</h3>

<p data-order-step="success">Votre commande a bien été enregistrée, elle vous sera livrée dans les plus brefs délais.</p>
<p class="layout-center"><img alt="Commande payée" src="<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: wwwUrl in /home/wabap32/sites/Restaurant (corrigé)/application/www/order/payment/success/SuccessView.phtml on line <i>6</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>359808</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/wabap32/sites/Restaurant (corrigé)/application/www/order/payment/success/SuccessView.phtml' bgcolor='#eeeeec'>.../SuccessView.phtml<b>:</b>0</td></tr>
</table></font>
/images/success.gif"></p>

<a class="button button-primary" href="<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: requestUrl in /home/wabap32/sites/Restaurant (corrigé)/application/www/order/payment/success/SuccessView.phtml on line <i>8</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>359808</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/wabap32/sites/Restaurant (corrigé)/application/www/order/payment/success/SuccessView.phtml' bgcolor='#eeeeec'>.../SuccessView.phtml<b>:</b>0</td></tr>
</table></font>
">Accueil</a>


<!-- Classes de gestion du formulaire de commande -->
<!-- Ce code JavaScript n'est chargé QUE depuis l'URL /order/payment/success -->
<script src="<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: wwwUrl in /home/wabap32/sites/Restaurant (corrigé)/application/www/order/payment/success/SuccessView.phtml on line <i>13</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>359808</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/wabap32/sites/Restaurant (corrigé)/application/www/order/payment/success/SuccessView.phtml' bgcolor='#eeeeec'>.../SuccessView.phtml<b>:</b>0</td></tr>
</table></font>
/js/classes/BasketSession.class.js"></script>
<script src="<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: wwwUrl in /home/wabap32/sites/Restaurant (corrigé)/application/www/order/payment/success/SuccessView.phtml on line <i>14</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>359808</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/wabap32/sites/Restaurant (corrigé)/application/www/order/payment/success/SuccessView.phtml' bgcolor='#eeeeec'>.../SuccessView.phtml<b>:</b>0</td></tr>
</table></font>
/js/classes/OrderForm.class.js"></script>