<h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>

<form class="generic-form" action="<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: requestUrl in /home/wabap32/sites/Restaurant (corrigé)/application/www/user/login/LoginView.phtml on line <i>3</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>358912</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/wabap32/sites/Restaurant (corrigé)/application/www/user/login/LoginView.phtml' bgcolor='#eeeeec'>.../LoginView.phtml<b>:</b>0</td></tr>
</table></font>
/user/login" method="POST">

	<aside class="error-message hidden">
		<h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
		<p><br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: errorMessage in /home/wabap32/sites/Restaurant (corrigé)/application/www/user/login/LoginView.phtml on line <i>7</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>358912</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/wabap32/sites/Restaurant (corrigé)/application/www/user/login/LoginView.phtml' bgcolor='#eeeeec'>.../LoginView.phtml<b>:</b>0</td></tr>
</table></font>
</p>
	</aside>

	<fieldset>
		<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="email">E-mail :</label>
				<input id="email" type="text" name="email" data-required data-name="E-mail" value="<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: email in /home/wabap32/sites/Restaurant (corrigé)/application/www/user/login/LoginView.phtml on line <i>15</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>358912</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/wabap32/sites/Restaurant (corrigé)/application/www/user/login/LoginView.phtml' bgcolor='#eeeeec'>.../LoginView.phtml<b>:</b>0</td></tr>
</table></font>
">
			</li>
			<li>
				<label for="password">Mot de passe :</label>
				<input id="password" type="password" name="password" data-required data-name="Mot de passe">
			</li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Connexion">
			<a class="button button-cancel small" href="<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: requestUrl in /home/wabap32/sites/Restaurant (corrigé)/application/www/user/login/LoginView.phtml on line <i>27</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>358912</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/wabap32/sites/Restaurant (corrigé)/application/www/user/login/LoginView.phtml' bgcolor='#eeeeec'>.../LoginView.phtml<b>:</b>0</td></tr>
</table></font>
">Annuler</a>
		</li>
	</ul>
</form>